server:
  servlet:
    contextPath: /pw

spring:
  application:
    name: Propertyware rest application
  jpa:
    show-sql: false
  h2:
    console:
      enabled: true
  profiles:
    active: ${spring.profiles.active:local}
