server:
  servlet:
    contextPath: /
  port: 8082

spring:
  application:
    name: Propertyware rest application
  jpa:
    show-sql: false
  h2:
    console:
      enabled: true
  profiles:
    active: sit

