#spring.h2.console.enabled=true
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
#    url: jdbc:h2:mem:dcbapp
#    driverClassName: org.h2.Driver
     url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/pw_rest_test_tool?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
     driverClassName: com.mysql.cj.jdbc.Driver
     username: root
     password: Password1
  hibernate:
    ddl: true
  #h2:
  #console:
  #enabled: true
